language: python
python:
  - 3.8
services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t leersma/pneumo-detect:latest .

deploy:
  provider: script
  script:
    docker push leersma/pneumo-detect:latest;
  on:
    branch: main